blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
 url(r'^$', views.blog_home, name="blog_home"),
 url(r'^blog/list$', views.blog_list, name="blog_list"),
 url(r'^blog/(?P<pk>\d+)/$', views.blog_detail, name="blog_detail"),
 url(r'^blog/(?P<pk>\d+)/edit$', views.blog_edit, name="blog_edit"),
 url(r'^blog/new$', views.blog_new, name="blog_new"),
 url(r'^blog/game$', views.blog_game, name="blog_game"),
 url(r'^blog/timer', views.blog_timer, name="blog_timer"),
 url(r'^blog/canvas$', views.blog_canvas, name="blog_canvas"),
 url(r'^blog/image', views.blog_image, name="blog_image"),
 url(r'^blog/(?P<pk>\d+)/remove', views.blog_remove, name="blog_remove"),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth import views

urlpatterns = [
    url(r'', include('blog.urls', namespace="blog")),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page':'/'}),
]

blog/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.CharField(max_length=100, default="guest")
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    photo = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.title

blog/forms.py
from django import  forms

from .models import Post


class PostForm(forms.ModelForm) :

    class Meta:
        model = Post
        fields = ('title', 'author', 'text',)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import Post
from .forms import PostForm
from django.contrib.auth.decorators import login_required


def blog_home(request):
    posts = Post.objects.order_by('id')[:5].reverse()
    return render(request, 'blog/blog_home.html', {'posts': posts})


def blog_list(request):
    contacts = Post.objects.order_by('id').reverse()
    paginator = Paginator(contacts, 10)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/blog_list.html', {'posts': posts})


def blog_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/blog_detail.html', {'post': post})


def blog_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save()
            return redirect('blog:blog_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/blog_edit.html', {'form':form})


@login_required
def blog_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save()
            return redirect('blog:blog_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/blog_edit.html', {'form':form})


@login_required
def blog_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('blog:blog_list')


def blog_game(request):
    return render(request, 'blog/blog_game.html', {})


def blog_canvas(request):
    return render(request, 'blog/blog_canvas.html', {})


def blog_timer(request):
    return render(request, 'blog/blog_timer.html', {})


def blog_image(request):
    return render(request, 'blog/blog_image.html', {})

blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Gugi|Nanum+Gothic&amp;subset=korean">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}?var=20180829">
    <link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}">
    <title>PORTFOLIO</title>
</head>
<body style="margin:0;">
<div class="bodyDiv">
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="top-login">
            {% if user.is_authenticated %}
            <p>Hello {{ user.username }} (<a href="{% url 'logout' %}">Logout</a>)</p>
            {% else %}
            <a href="{% url 'login' %}"><span class="glyphicon glyphicon-lock"></span></a>
            {% endif %}
        </div>
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="navbar-toggle-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'blog:blog_home' %}">Home</a></li>
                    <li><a href="{% url 'blog:blog_list' %}">PostList</a></li>
                    <li><a href="{% url 'blog:blog_timer' %}">Timer</a></li>
                    <li><a href="{% url 'blog:blog_canvas' %}">Canvas</a></li>
                    <li><a href="{% url 'blog:blog_image' %}">ImageZoom</a></li>
                    <!--<li><a href="{% url 'blog:blog_game' %}">Game</a></li>-->
                </ul>
            </div>
        </div>
    </div>
</nav>


<div class="jumbotron header text-center">
    <h1 class="headH" style="margin:0;">PORTFOLIO</h1>
    <p class="headP" style="font-size: 13px;">핸드폰보다 타블렛, 데스크탑(크롬)에 최적화 되어있습니다.</p>
</div>

<div class="container-fluid" style="margin-bottom: 50px;">
    <div class="blog-body">
        {% block content %}
        {% endblock %}

        {% block scripts %}
        {% endblock %}
    </div>
</div>

<footer class="footer footer-fixed-bottom text-center">
    <p><strong>email: yuraham@naver.com / hyrfortheweb@gmail.com</strong></p>
</footer>
</div>
</body>
</html>

blog/templates/blog/blog_canvas.html
{% extends 'blog/base.html' %}
{% load staticfiles %}

<!--{% block extrastyle %}{% static "css/canvas.css" %}{% endblock %}-->
{% block content %}
<div id="heremyCanvas">
    <div class="childHeremy">
        <p class="canvasTop">My Canvas</p>
        <div class="canvasItem">
            <canvas id="myCanvas" width="700" height="520"></canvas>
            <div class="canvasBtn">
                <p id="Eraser" class="myBtn btn">Eraser</p>
                <p id="delAll" class="myBtn btn">Delete</p>
            </div>
            <div id="brushBtndiv">
                <span>Brush Size</span>
                <div id="brushBtn">
                    <ul>
                        <li class="btnn btn" value="1">1</li>
                        <li class="btnn btn" value="3">2</li>
                        <li class="btnn btn" value="6">3</li>
                        <li class="btnn btn" value="10">4</li>
                    </ul>
                    <ul>
                        <li class="btnn btn" value="15">5</li>
                        <li class="btnn btn" value="20">6</li>
                        <li class="btnn btn" value="25">7</li>
                        <li class="btnn btn" value="30">8</li>
                    </ul>
                </div>
            </div>
            <div id="brushColor">
                <span>Brush Color</span>
                <div id="thisC"><span>#000000</span></div>
                <div class="colorful">
                    <p id="Redc">Red</p>
                    <input type="range" id="cRed" class="cRed" min="0" max="255" value="0">
                </div>
                <div class="colorful">
                    <p id="Greenc">Green</p>
                    <input type="range" id="cGreen" class="cGreen" min="0" max="255" value="0">
                </div>
                <div class="colorful">
                    <p id="Bluec">Blue</p>
                    <input type="range" id="cBlue" class="cBlue" min="0" max="255" value="0">
                </div>
            </div>
            <div id="eText">
                <p>이미지 저장: 우클릭</p>
                <p>다른 이름으로 저장</p>
            </div>
        </div>
    </div>
</div>
    <div >
        <div class="canvasText">
            <div class="explClock">
                <p class="explP"><strong>사용법</strong></p>
                <div id="explText">
                    <p><strong>1. 캔버스 화면에 마우스를 클릭 후 움직이면 선이 그려집니다.</strong></p>
                    <p><strong>2. Eraser 버튼 클릭 시 자동으로 #fff 색으로 변경, 지우개로써 활용할 수 있습니다.</strong></p>
                    <p><strong>3. Delete 버튼 클릭 시 화면이 초기화됩니다.</strong></p>
                    <p><strong>4. BrushSize의 1~8 버튼 클릭 시 각각의 브러시 사이즈로 변경됩니다.</strong></p>
                    <p><strong>5. Brush Color의 Red, Green, Blue의 값 변경 시 브러시 색상 또한 변경됩니다.</strong></p>
                    <p><strong>6. 이미지는 그림을 그린 캔버스의 우 클릭 후 다른 이름으로 저장을 이용합니다.</strong></p>
                    <div class="hardText">
                        <button type="button" class="btn" data-toggle="collapse" data-target="#innerHard">진행하며 어려웠던 점</button>
                        <div id="innerHard" class="collapse">
                            <p class="innerP firP">가장 진행하면서 어려웠던 점은 뭐니뭐니해도 선을 긋는 것이었습니다.
                                처음엔 W3shcools의 게임 예제를 진행했던 것을 바탕으로 캔버스를 만들어 보려 했었는데 선을 빠르게 그리지 않으면 다 점으로써 띄어 나오는 것 때문에 한참을 고민했습니다.
                                선생님께서 무브투로써 캔버스에 선을 긋는 것에 대한 힌트를 주셔서 한참을 고민하고 또 해보다 결국 구글링을 통해 또 힌트를 얻어 진행할 수 있었습니다.
                            </p>

                            <p class="innerP">
                                게다가 색상을 바꿀 때 헥사에서 rgb로, rgb에서 헥사로 가는 것이 생각보다 복잡해 한참을 또 헤맸었습니다.
                                이를 변경하는 데엔 제가 알지못했던 새로운 방식과 기존의 제가 알던 것들이 조합되어야 했고, 여태 내가 알지 못하는 것들이 너무 많다는 생각이 들었습니다.
                                종합적으로 기본적으로 배운 내용에서 응용해 나가는 게 더욱 어렵다는 걸 깨달았습니다.
                            </p>

                            <p class="innerP lasP">-2018.08.31</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/canvas.js' %}"></script>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="container">
    <div class="page-header">
        <h1>{{ post.title }}</h1>
        <small> | create : {{ post.created_date|date:'Y-m-d H:i' }} </small>
    </div>
    <p>{{post.text}}</p>
    <br>
    <hr class="d-sm-none">
    {% if user.is_authenticated %}
        <a class="btn btn-lg" href="{% url 'blog:blog_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        <a class="btn btn-lg" href="{% url 'blog:blog_remove' pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
    {% endif %}
</div>
{% endblock %}

blog/templates/blog/blog_edit.html
{% extends 'blog/base.html' %}
{% load staticfiles %}

{% block extrastyle %}{% static "css/edit.css" %}{% endblock %}

{% block content %}

<div class="container">
    <div class="page-header">
        <h1>New Post</h1>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        <div class="container">
            <p class="postText"><strong>Title:</strong></p>
            {{ form.title }}
            <p class="postText"><strong>Author:</strong></p>
            {{ form.author }}
            <p class="postText"><strong>Text:</strong></p>
            {{ form.text }}
            <button class="btn save" type="submit"><strong>Save</strong></button>
        </div>
    </form>
</div>
{% endblock %}

blog/templates/blog/blog_game.html
{% extends 'blog/base.html' %}

{% block content %}

<h2 style="text-align: center">준비중</h2><br><br>

{% endblock %}

blog/templates/blog/blog_home.html
{% extends 'blog/base.html' %}
{% load staticfiles %}

{% block extrastyle %}{% static "css/home.css" %}{% endblock %}

{% block content %}

<div class="home" >
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="panel panel-default pal">
                    <div class="panel-heading">
                        <h2 class="hhead">: About me</h2>
                    </div>
                    <div class="panel-body">
                        <h4 class="hbody"><strong>"꿈꾸는 미래의 웹개발자"</strong></h4>
                        <div class="pbody">
                            <p class="momP"><strong>이름: </strong></p>
                            <p class="childP">함유라 HamYura</p>
                            <p class="momP"><strong>웹개발: </strong></p>
                            <p class="childP">2018.05.24 ~ </p>
                            <p class="momP"><strong>사용 가능 언어: </strong></p>
                            <p class="childP">2018.08.31기준<br>html, css, javascript, python, django</p>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default pal">
                    <div class="panel-body">
                        <div class="pbody">
                            <p class="momP"><strong>홈페이지 제작 언어: </strong></p>
                            <p class="childP">Python(Django), HTML, CSS(Bootstrap), JavaScript</p>
                            <p class="momP"><strong>참고한 곳: </strong></p>
                            <p class="childP">Djangogirls, w3schools, google search</p>
                            <p class="momP"><strong>사용 프로프램: </strong></p>
                            <p class="childP">pycharm community, visual studio code</p>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default pal2">
                    <div class="panel-heading">
                        <h2 class="updateH"><strong>업데이트 내역</strong></h2>
                    </div>
                    <div class="panel-body">
                        <div class="pbody">
                            <p class="childP">20180904</p>
                            <p class="childP"><small>-홈페이지 PostList의 새글쓰기 수정</small></p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-9" >
                <div class="bimgTable">
                    <img class="bimg" src="{% static 'image/flamingo.jpg' %}" alt="flamingo">
                </div>
                <hr class="d-sm-none">
                <div class="home-posts">
                    <h2 class="postText"><a href="{% url 'blog:blog_list' %}"><strong>more post</strong></a></h2>
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th class="idTh">ID</th>
                            <th class="dateTh">DATE</th>
                            <th>TITLE</th>
                            <th class="writerTh">WRITER</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for post in posts %}
                        <tr>
                            <td class="tdText">{{ post.id }}</td>
                            <td class="tdText"><small>{{ post.created_date|date:'Y-m-d H:i'}}</small></td>
                            <td class="tdTitle"><a href="{% url 'blog:blog_detail' pk=post.pk %}">{{ post.title }}</a></td>
                            <td class="tdText">{{ post.author }}</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_image.html
{% extends 'blog/base.html' %}
{% load staticfiles %}

{% block extrastyle %}{% static "css/image.css" %}{% endblock %}

{% block content %}
<div class="container">
    <p class="imgZoom"><strong>Image Zoom</strong></p>
    <p class="childText">이미지 파일을 불러와 확대해 볼 수 있는 곳입니다.</p>
    <hr class="d-sm-none">
    <div id="totalImg">
        <label for="imgInput" class="inputLabel">Image Upload</label>
        <input id="imgInput" type="file" accept=".png, .jpg, .jpeg">
        <div class="imgdiv">
            <img id="thisImg">
        </div>
        <div class="zoomBox">
            <canvas id="imgCanvas" width="350" height="300"></canvas>
            <p id="coordi"></p>
        </div>
    </div>
</div>
<div>
    <div class="imageText">
        <div class="explImage">
            <p class="explP"><strong>사용법</strong></p>
            <div id="explText">
                <p><strong>1. 이미지를 불러와 미리볼 수 있습니다.</strong></p>
                <p><strong>2. 불러온 이미지 클릭시 오른쪽 캔버스에 확대된 모습을 볼 수 있습니다.</strong></p>
                <p><strong>3. coodinates를 통해 자신이 어디를 클릭했는지 알 수 있습니다.</strong></p>
                <div class="hardText">
                    <button type="button" class="btn" data-toggle="collapse" data-target="#innerHard">진행하며 어려웠던 점</button>
                    <div id="innerHard" class="collapse">
                        <p class="innerP firP">이미지 확대는 전부터 관심이 있었습니다. 이미지 파일을 올리고, 그걸 가져다 확대시켜 본다는 게 아직 개발 극초보였던 저에게는 엄청 신선하게 다가왔습니다.
                            차근차근 인풋을 배우고, 이벤트를 배우다보니 어렴풋이 어떻게 진행해야 할 지 머릿속으로 그려졌습니다.
                        </p>

                        <p class="innerP">
                            실제로 진행할 때 제일 버벅거렸던 곳은 마우스로 클릭한 곳의 좌표를 확대 화면에 불러오는 곳이었습니다.
                            처음에 마우스로 클릭한 곳의 좌표와 확대된 곳의 위치가 다르다는 것을 알아차리고, 이걸 어떻게 해결해야 할지 한참을 고민했었습니다. 그리고 알아냈죠.
                            화면에 띄워주는 이미지의 크기를 정해 놓는다 해도, 실제 마우스로 클릭한 좌표는 오리지널 사이즈로 지정된다는 것을.
                        </p>

                        <p class="innerP">
                            그래서 결국 또다시 타이머에서 이용했던 비율을 이용해 해결해 나갔습니다. 한번 경험해 본 공식이다보니 타이머를 했을 때에 비해 그렇게 오래 걸리지는 않았었습니다.
                            이미지를 다룬다는 게 생각보다 어렵다는 걸 다시금 깨달았고, 그리고 그만큼 재밌다는 것도 깨달은 즐거운 시간이었습니다.
                        </p>

                        <p class="innerP lasP">-2018.08.31</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/image.js' %}"></script>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'blog/base.html' %}
{% load staticfiles %}

{% block extrastyle %}{% static "css/list.css" %}{% endblock %}

{% block content %}
<div class="myList">
    <div class="listCont">
        <p class="freePost"><strong>자유게시판</strong></p>
        <p class="childText">로그인 없이도 이용 가능한 게시판입니다. 관리자의 사정에 따라 게시글이 삭제, 수정될 수 있습니다.</p>
        <hr class="d-sm-none">

        <table class="table table-hover">
            <thead>
            <tr>
                <th class="idTh">ID</th>
                <th class="dateTh">DATE</th>
                <th>TITLE</th>
                <th class="writerTh">WRITER</th>
            </tr>
            </thead>
            <tbody>
            {% for post in posts %}
            <tr>
                <td class="tdText">{{ post.id }}</td>
                <td class="tdText"><small>{{ post.created_date|date:'Y-m-d H:i'}}</small></td>
                <td class="tdTitle"><a href="{% url 'blog:blog_detail' pk=post.pk %}">{{ post.title }}</a></td>
                <td class="tdText">{{ post.author }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        <p class="plus-post"><a href="{% url 'blog:blog_new' %}" class="glyphicon glyphicon-plus"></a></p>

        <div class="pagination" style="margin-top:10px; margin-bottom: 10px;">
            <span class="step-links">
                {% if posts.has_previous %}
                    <a href="?page={{ posts.previous_page_number }}">뒤로</a>
                {% endif %}

                <span class="current">
                    {{ posts.number }} . {{ posts.paginator.num_pages }}
                </span>

                {% if posts.has_next %}
                    <a href="?page={{ posts.next_page_number }}">다음</a>
                {% endif %}
            </span>
        </div>
    </div>

</div>
{% endblock %}

blog/templates/blog/blog_timer.html
{% extends 'blog/base.html' %}
{% load staticfiles %}

{% block extrastyle %}{% static "css/timer.css" %}{% endblock %}

{% block content %}

<div class="out-line clockTime">
    <!--시계-->
    <div class="clockBox well">
        <p class="introdu"><strong>Timer</strong></p>
        <div>
            <span id="clockBody"></span>
        </div>
        <div class="clockInfoDiv">
            <span>시간설정 후 시작버튼 클릭</span><br>
            <span>정지버튼 클릭시 일시정지</span><br>
            <span>재시작 버튼 클릭시 리셋</span>
        </div>
        <button id="clockbtn">시작</button>
        <button id="clockbtn2">재시작</button>
    </div>
    <div class="timeText">
        <div class="explClock">
            <p class="explP"><strong>사용법</strong></p>
            <div class="explText">
                <p><strong>1. 타이머의 모래시계 그림 부분을 클릭한다.</strong></p>
                <p><strong>2. 뜨는 창에 지정할 시간을 입력한다.</strong></p>
                <p><strong>3. 시작 버튼을 누른다.</strong></p>
                <p><strong>4. 모든 시간이 끝나면 stop글씨와 함께 종료된다.</strong></p>
                <div class="inexplText">
                    <p>-정지버튼 클릭 시 일시정지를 할 수 있다.</p>
                    <p>-재시작 버튼 클릭시 모든 시간 설정이 리셋된다.</p>
                    <p>-시간 설정은 꼭 01:03의 형태가 아니어도 된다.</p>
                    <div class="explText">
                        <p>	1:3 > 01:03</p>
                        <p>	0:3 > 00:03</p>
                        <p>	:3 > 00:03</p>
                    </div>
                    <p>-단, 시간 설정시 ':'와 뒤의 숫자는 필수.</p>
                    <p>-최대 시간은 15:00, 최소 시간은 00:01</p>
                </div>
            </div>
            <div class="hardText">
                <button type="button" class="btn" data-toggle="collapse" data-target="#innerHard">진행하며 어려웠던 점</button>
                <div id="innerHard" class="collapse">
                    <p class="innerP firP">가장 어려웠던 점은 다름 아닌 수학공식의 적용이었습니다.
                    timer의 모래시계 속 모래가 시간이 가는 것에 따라 y의 값이 변환이 되어야 하는데, 이는 비율로 적용해야 했습니다.
                    비율의 공식은 선생님께서 도와주셨는데 'y의 높이=(현재 시간*처음 높이)/입력시간'이라는 공식을 어떻게 대입해야 할지 한참을 고민했었습니다. 답은 다 나와있었는데도요!
                    백분율이 필요한가 고민도 해보고, 퍼센트도 구해보고. 여러 가지 일을 해보다 결국 처음으로 돌아와 저 공식을 곰곰이 고민해 봤습니다. 그리고 깨달았죠. 저게 정답 그 자체라는걸.
                    그 뒤로도 한참을 헤맸습니다. 비록 간단하고도 일상생활에 많이 쓰이는 공식이지만 가우스의 공식, 사칙연산 등을 제외하고 수학 공식을 이렇게 본격적으로 코드에 사용하는 건 처음이었으니까요.
                    </p>

                    <p class="innerP">
                    어느 정도 감을 잡아가자 두 번째 문제가 생겼었습니다. 수학 공식처럼 아주 헷갈리는게 아닌 그래도 감은 오지만 조금 헤맸던 문제. 현재 흘러간 시간의 값을 어떻게 가져와야 할지. 그리고 또 한참을 구글링과 더불어 W2Schools의 내용을 읽어보다 방법을 찾았습니다. 바로 전역 변수 스코프를 이용하는 방법이었죠.
                    아직 제가 전역 변수 스코프와 지역 변수 스코프라는 기초에 약하다는 증거처럼 다가왔습니다. 조금 더 열심히 해야겠지요.
                    먼저 전역 스코프로 변수를 선언한 뒤, 나중에 현재 시간을 구하는 함수를 작성할 때 변수에 값을 넣어주는 걸로 간단히 해결했습니다.
                    </p>

                    <p class="innerP">
                    이 포트폴리오를 작성하면서 가장 먼저 만들었던 프로그램인 만큼, 완성했을 때의 기쁨은 아직도 잊을 수 없습니다. 물론 부족한 점도 있고, 아직 보완해야 할 곳도 많다는 걸 잊지 않았습니다.
                    주기적으로 업데이트 예정입니다.
                    </p>

                    <p class="innerP lasP">-2018.08.31</p>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}
<script src="{% static 'js/timer.js' %}"></script>
{% endblock %}